#ifndef FLV_ANALYSIS_H
#define FLV_ANALYSIS_H

#define FLV_HEADER_SIZE 9
#define FLV_TAGSIZE_SIZE 4
#define FLV_TAG_HEADER_SIZE 11

#define FLV_TAG_TYPE_AUDIO 8
#define FLV_TAG_TYPE_VIDEO 9
#define FLV_TAG_TYPE_DATA 18

#define FLV_SOUND_FORMAT_MP3 2
#define FLV_SOUND_FORMAT_AAC 10
#define FLV_SOUND_FORMAT_SPEEX 11

#define FLV_SOUND_TYPE_MONO 0
#define FLV_SOUND_TYPE_STEREO 1

#define FLV_VIDEO_CODEC_AVC 7

#define AVC_NAL_UNIT_TYPE_UNSPECIFIED 0
#define AVC_NAL_UNIT_TYPE_SLICE_NONIDR 1
#define AVC_NAL_UNIT_TYPE_SLICE_PARTITION_A 2
#define AVC_NAL_UNIT_TYPE_SLICE_PARTITION_B 3
#define AVC_NAL_UNIT_TYPE_SLICE_PARTITION_C 4
#define AVC_NAL_UNIT_TYPE_SLICE_IDR 5
#define AVC_NAL_UNIT_TYPE_SEI 6
#define AVC_NAL_UNIT_TYPE_SPS 7
#define AVC_NAL_UNIT_TYPE_PPS 8
#define AVC_NAL_UNIT_TYPE_AUD 9

#define FLV_DATA_VALUE_TYPE_NUMBER 0
#define FLV_DATA_VALUE_TYPE_BOOLEAN 1
#define FLV_DATA_VALUE_TYPE_STRING 2
#define FLV_DATA_VALUE_TYPE_OBJECT 3
#define FLV_DATA_VALUE_TYPE_ECMA 8
#define FLV_DATA_VALUE_TYPE_LONGSTRING 12
#define BREAK_UNSUPPORTTED_DATA_TYPE "break unsupported data type: %d\n"

#define SPLIT_LINE "---------------------------------------------\n"

#define ERR_INPUT_EOF 100

int analysis();

#endif //FLV_ANALYSIS_H
